---
pixi_version: "latest"
pixi_install_url: "https://pixi.sh/install.sh"
pixi_install_dir: "/usr/local/bin"

# GitHub repository details
ai_tools_repo: "https://github.com/Leiden-Cell-Observatory/AI_tools_pixi.git"
ai_tools_dir: "/opt/AI_tools_pixi"

# List of pixi environments to install (folder names from the repo)
pixi_environments:
  - biapy
  - CAREamics
  - cellpose
  - micro_sam
  - omero
  - spotiflow
  - stardist
  - trackastra
