---
- name: Install system dependencies
  ansible.builtin.apt:
    name: 
      - wget
      - unzip
      - libxcb-xinerama0
    state: present
    # This prevents the whole script from crashing if the VM mirrors are messy
    update_cache: yes
  ignore_errors: yes 

- name: Download and Extract QuPath
  ansible.builtin.unarchive:
    src: "{{ qupath_url }}"
    dest: "/opt"
    remote_src: yes
    creates: "/opt/QuPath/bin/QuPath"

- name: Create Common Data directory
  ansible.builtin.file:
    path: "{{ common_data_dir }}"
    state: directory
    mode: '0777'

- name: Download Extensions from Zenodo
  ansible.builtin.unarchive:
    src: "{{ common_data_url }}"
    dest: "{{ common_data_dir }}"
    remote_src: yes

- name: Configure QuPath preferences
  ansible.builtin.shell: |
    export JAVA_TOOL_OPTIONS="-Djava.awt.headless=true"
    /opt/QuPath/bin/QuPath script "{{ role_path }}/files/QuPath_setPaths.groovy"
  # This runs as the researcher user (ubuntu) to set their specific preferences
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Install Desktop Launcher
  ansible.builtin.template:
    src: qupath.desktop.j2
    dest: "/usr/share/applications/qupath.desktop"
    mode: "0644"